[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
# Name used to install with pip:
name = "gregs_rng"

# Current version of this package:
version = "0.1.0"

# Description published on PyPI:
description = "Random Number Generator using the Linear Congruential Generation Method"

readme = "README.md"

requires-python = ">=3.10.12"

authors = [
    {name = "Greg Dorshimer"}
]

# Keywords for help finding the package:
keywords = ["random", "rng", "statistics", "linear congruential generator"]

# PyPI Classifiers describing the package:
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]


[tool.setuptools]
package-dir = {"" = "src"}


[project.urls]
Homepage = "https://github.com/gregdorshimer/gregs_rng"
Issues = "https://github.com/gregdorshimer/gregs_rng/issues"


[tool.setuptools.packages.find]
where = ["src"]